name: Deploy React + Vite to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (optional, ignore errors)
        run: npm run lint || true

      - name: Build React + Vite app
        run: npm run build

      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/"
          target: "/var/www/html/front_end"

      - name: SSH into EC2 and serve the app (optional)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install serve globally if not installed
            if ! command -v serve > /dev/null; then
              npm install -g serve
            fi
            # Kill any existing serve processes on port 3000 (optional)
            pkill -f "serve -s /var/www/html/front_end" || true
            # Start serving the build folder on port 3000 in the background
            nohup serve -s /var/www/html/front_end -l 3000 > serve.log 2>&1 &
