name: Deploy React + Vite to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (optional, with fix)
        run: |
          npm run lint -- --fix # Attempt to fix linting errors automatically
          # If the fix doesn't resolve all errors and you want the workflow to continue,
          # you can add || true to the end of the line.  However, it's generally
          # better to fix the errors properly.
          # Example:  npm run lint -- --fix || true

      - name: Build React + Vite app
        run: npm run build

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: dist/
          target: /var/www/html/front_end  # Deploy to the correct web root

      - name: SSH into EC2 and configure/start the app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure the target directory exists
            sudo mkdir -p /var/www/html/front_end
            sudo chown -R $USER:$USER /var/www/html/front_end
            # Copy the build output (already done by scp)
            #  No need to repeat the copy here
            # Set up permissions (if needed) -  Make sure web server can read the files
            sudo chmod -R 755 /var/www/html/front_end
            # Install serve (if you're using it) or any other production server.
            npm install -g serve  # Install globally
            # Start the server.  Change the port if needed.
            serve -s /var/www/html/front_end -l 3000
            # If you were using pm2, the commands would look like this:
            # npm install -g pm2
            # pm2 start /var/www/html/front_end -name "my-react-app"
