name: Deploy Frontend to EC2 using rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync front_end folder to EC2 via rsync
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Make sure target directory exists
            mkdir -p /var/www/html/front_end

      - name: Run rsync to copy files
        run: |
          rsync -avz --delete --exclude='.git*' -e "ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no" ./front_end/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/front_end/
