name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy front_end folder to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}          # EC2 public IP or hostname
          username: ${{ secrets.EC2_USER }}      # EC2 user, e.g. ubuntu/ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}        # Your private SSH key stored in GitHub Secrets
          source: "front_end/**"
          target: "/var/www/html/front_end"

      - name: SSH into EC2 and run npm commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/front_end
            npm install --production
            if ! command -v serve > /dev/null; then
              npm install -g serve
            fi
            pkill -f "serve -s dist" || true
            nohup serve -s dist -l 3000 > serve.log 2>&1 &
